apiVersion: triggers.tekton.dev/v1alpha1
kind: Interceptor
metadata:
  name: slack-interceptor
  labels:
    server/type: http
spec:
    clientConfig:
      service:
        name: slack-webhook-interceptor
        namespace: sample-app