apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-webhook-interceptor
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slack-webhook-interceptor
  template:
    metadata:
     labels:
       app.kubernetes.io/name: slack-webhook-interceptor
    spec:
      serviceAccountName: sample-app-sa
      containers:
        - name: slack-webhook-interceptor
          image: quay.io/ilan_pinto/slack-webhook:v7
---
apiVersion: v1
kind: Service
metadata:
  name: slack-webhook-interceptor
  namespace: sample-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: slack-webhook-interceptor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      