apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterInterceptor
metadata:
  name: slack-interceptor
spec:
    clientConfig:
      service:
        name: slack-webhook-interceptor
        namespace: sample-app