apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo-sample-app
  namespace: sample-app
resources:
- namespace.yaml

# apply secrets 
- Secrets/slack-webhook-secret.yaml

# apply RBAC 
- Roles/cluster-role.yaml
- Roles/service-account.yaml
- Roles/cluster-admin-role-binding.yaml

# apply task 
- Tasks/git-clone.yaml 
- Tasks/s2i.yaml
- Tasks/send-to-webhook-slack.yaml 
  
# pipeline 
- Pipeline/build-pipeline.yaml


# webhook 
- Interceptor/interceptor.yaml
- Interceptor/interceptor-service.yaml

# trigger
- Trigger/event-listener.yaml
- Trigger/trigger-template.yaml
# run 
- PipelineRun/sample-app-pvc.yaml 
# - PipelineRun/build-pipeline-run.yaml

