apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-admin
rules:
- apiGroups:
  - ""  
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - configmaps/status
  - secrets
  - namespaces
  - serviceaccounts
  - pods/log
  - statefulsets
  - clusterinterceptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - deployments/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  - clusterrolebindings
  - rolebindings
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - "triggers.tekton.dev"
  resources:
  - "*"
  verbs:
  - "*"